# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/jasper/Documents/uni/2025 sem1/cits3003/CITS3003Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/jasper/Documents/uni/2025 sem1/cits3003/CITS3003Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.2.5-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/jasper/Documents/uni/2025 sem1/cits3003/CITS3003Project/CMakeFiles" "/home/jasper/Documents/uni/2025 sem1/cits3003/CITS3003Project//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/jasper/Documents/uni/2025 sem1/cits3003/CITS3003Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cits3003_project

# Build rule for target.
cits3003_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cits3003_project
.PHONY : cits3003_project

# fast build rule for target.
cits3003_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/build
.PHONY : cits3003_project/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f lib/glad/CMakeFiles/glad.dir/build.make lib/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/update_mappings.dir/build.make lib/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/glm/CMakeFiles/uninstall.dir/build.make lib/glm/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f lib/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build.make lib/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f lib/assimp/code/CMakeFiles/assimp.dir/build.make lib/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named stb

# Build rule for target.
stb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb
.PHONY : stb

# fast build rule for target.
stb/fast:
	$(MAKE) $(MAKESILENT) -f lib/stb/CMakeFiles/stb.dir/build.make lib/stb/CMakeFiles/stb.dir/build
.PHONY : stb/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f lib/imgui/CMakeFiles/imgui.dir/build.make lib/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named tinyfiledialogs

# Build rule for target.
tinyfiledialogs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyfiledialogs
.PHONY : tinyfiledialogs

# fast build rule for target.
tinyfiledialogs/fast:
	$(MAKE) $(MAKESILENT) -f lib/tinyfiledialogs/CMakeFiles/tinyfiledialogs.dir/build.make lib/tinyfiledialogs/CMakeFiles/tinyfiledialogs.dir/build
.PHONY : tinyfiledialogs/fast

src/feature/simplex.o: src/feature/simplex.cpp.o
.PHONY : src/feature/simplex.o

# target to build an object file
src/feature/simplex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/feature/simplex.cpp.o
.PHONY : src/feature/simplex.cpp.o

src/feature/simplex.i: src/feature/simplex.cpp.i
.PHONY : src/feature/simplex.i

# target to preprocess a source file
src/feature/simplex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/feature/simplex.cpp.i
.PHONY : src/feature/simplex.cpp.i

src/feature/simplex.s: src/feature/simplex.cpp.s
.PHONY : src/feature/simplex.s

# target to generate assembly for a file
src/feature/simplex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/feature/simplex.cpp.s
.PHONY : src/feature/simplex.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rendering/cameras/FlyingCamera.o: src/rendering/cameras/FlyingCamera.cpp.o
.PHONY : src/rendering/cameras/FlyingCamera.o

# target to build an object file
src/rendering/cameras/FlyingCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/cameras/FlyingCamera.cpp.o
.PHONY : src/rendering/cameras/FlyingCamera.cpp.o

src/rendering/cameras/FlyingCamera.i: src/rendering/cameras/FlyingCamera.cpp.i
.PHONY : src/rendering/cameras/FlyingCamera.i

# target to preprocess a source file
src/rendering/cameras/FlyingCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/cameras/FlyingCamera.cpp.i
.PHONY : src/rendering/cameras/FlyingCamera.cpp.i

src/rendering/cameras/FlyingCamera.s: src/rendering/cameras/FlyingCamera.cpp.s
.PHONY : src/rendering/cameras/FlyingCamera.s

# target to generate assembly for a file
src/rendering/cameras/FlyingCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/cameras/FlyingCamera.cpp.s
.PHONY : src/rendering/cameras/FlyingCamera.cpp.s

src/rendering/cameras/PanningCamera.o: src/rendering/cameras/PanningCamera.cpp.o
.PHONY : src/rendering/cameras/PanningCamera.o

# target to build an object file
src/rendering/cameras/PanningCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/cameras/PanningCamera.cpp.o
.PHONY : src/rendering/cameras/PanningCamera.cpp.o

src/rendering/cameras/PanningCamera.i: src/rendering/cameras/PanningCamera.cpp.i
.PHONY : src/rendering/cameras/PanningCamera.i

# target to preprocess a source file
src/rendering/cameras/PanningCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/cameras/PanningCamera.cpp.i
.PHONY : src/rendering/cameras/PanningCamera.cpp.i

src/rendering/cameras/PanningCamera.s: src/rendering/cameras/PanningCamera.cpp.s
.PHONY : src/rendering/cameras/PanningCamera.s

# target to generate assembly for a file
src/rendering/cameras/PanningCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/cameras/PanningCamera.cpp.s
.PHONY : src/rendering/cameras/PanningCamera.cpp.s

src/rendering/imgui/ImGuiImpl.o: src/rendering/imgui/ImGuiImpl.cpp.o
.PHONY : src/rendering/imgui/ImGuiImpl.o

# target to build an object file
src/rendering/imgui/ImGuiImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/imgui/ImGuiImpl.cpp.o
.PHONY : src/rendering/imgui/ImGuiImpl.cpp.o

src/rendering/imgui/ImGuiImpl.i: src/rendering/imgui/ImGuiImpl.cpp.i
.PHONY : src/rendering/imgui/ImGuiImpl.i

# target to preprocess a source file
src/rendering/imgui/ImGuiImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/imgui/ImGuiImpl.cpp.i
.PHONY : src/rendering/imgui/ImGuiImpl.cpp.i

src/rendering/imgui/ImGuiImpl.s: src/rendering/imgui/ImGuiImpl.cpp.s
.PHONY : src/rendering/imgui/ImGuiImpl.s

# target to generate assembly for a file
src/rendering/imgui/ImGuiImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/imgui/ImGuiImpl.cpp.s
.PHONY : src/rendering/imgui/ImGuiImpl.cpp.s

src/rendering/imgui/ImGuiManager.o: src/rendering/imgui/ImGuiManager.cpp.o
.PHONY : src/rendering/imgui/ImGuiManager.o

# target to build an object file
src/rendering/imgui/ImGuiManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/imgui/ImGuiManager.cpp.o
.PHONY : src/rendering/imgui/ImGuiManager.cpp.o

src/rendering/imgui/ImGuiManager.i: src/rendering/imgui/ImGuiManager.cpp.i
.PHONY : src/rendering/imgui/ImGuiManager.i

# target to preprocess a source file
src/rendering/imgui/ImGuiManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/imgui/ImGuiManager.cpp.i
.PHONY : src/rendering/imgui/ImGuiManager.cpp.i

src/rendering/imgui/ImGuiManager.s: src/rendering/imgui/ImGuiManager.cpp.s
.PHONY : src/rendering/imgui/ImGuiManager.s

# target to generate assembly for a file
src/rendering/imgui/ImGuiManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/imgui/ImGuiManager.cpp.s
.PHONY : src/rendering/imgui/ImGuiManager.cpp.s

src/rendering/renders/AnimatedEntityRenderer.o: src/rendering/renders/AnimatedEntityRenderer.cpp.o
.PHONY : src/rendering/renders/AnimatedEntityRenderer.o

# target to build an object file
src/rendering/renders/AnimatedEntityRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/AnimatedEntityRenderer.cpp.o
.PHONY : src/rendering/renders/AnimatedEntityRenderer.cpp.o

src/rendering/renders/AnimatedEntityRenderer.i: src/rendering/renders/AnimatedEntityRenderer.cpp.i
.PHONY : src/rendering/renders/AnimatedEntityRenderer.i

# target to preprocess a source file
src/rendering/renders/AnimatedEntityRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/AnimatedEntityRenderer.cpp.i
.PHONY : src/rendering/renders/AnimatedEntityRenderer.cpp.i

src/rendering/renders/AnimatedEntityRenderer.s: src/rendering/renders/AnimatedEntityRenderer.cpp.s
.PHONY : src/rendering/renders/AnimatedEntityRenderer.s

# target to generate assembly for a file
src/rendering/renders/AnimatedEntityRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/AnimatedEntityRenderer.cpp.s
.PHONY : src/rendering/renders/AnimatedEntityRenderer.cpp.s

src/rendering/renders/EmissiveEntityRenderer.o: src/rendering/renders/EmissiveEntityRenderer.cpp.o
.PHONY : src/rendering/renders/EmissiveEntityRenderer.o

# target to build an object file
src/rendering/renders/EmissiveEntityRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/EmissiveEntityRenderer.cpp.o
.PHONY : src/rendering/renders/EmissiveEntityRenderer.cpp.o

src/rendering/renders/EmissiveEntityRenderer.i: src/rendering/renders/EmissiveEntityRenderer.cpp.i
.PHONY : src/rendering/renders/EmissiveEntityRenderer.i

# target to preprocess a source file
src/rendering/renders/EmissiveEntityRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/EmissiveEntityRenderer.cpp.i
.PHONY : src/rendering/renders/EmissiveEntityRenderer.cpp.i

src/rendering/renders/EmissiveEntityRenderer.s: src/rendering/renders/EmissiveEntityRenderer.cpp.s
.PHONY : src/rendering/renders/EmissiveEntityRenderer.s

# target to generate assembly for a file
src/rendering/renders/EmissiveEntityRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/EmissiveEntityRenderer.cpp.s
.PHONY : src/rendering/renders/EmissiveEntityRenderer.cpp.s

src/rendering/renders/EntityRenderer.o: src/rendering/renders/EntityRenderer.cpp.o
.PHONY : src/rendering/renders/EntityRenderer.o

# target to build an object file
src/rendering/renders/EntityRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/EntityRenderer.cpp.o
.PHONY : src/rendering/renders/EntityRenderer.cpp.o

src/rendering/renders/EntityRenderer.i: src/rendering/renders/EntityRenderer.cpp.i
.PHONY : src/rendering/renders/EntityRenderer.i

# target to preprocess a source file
src/rendering/renders/EntityRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/EntityRenderer.cpp.i
.PHONY : src/rendering/renders/EntityRenderer.cpp.i

src/rendering/renders/EntityRenderer.s: src/rendering/renders/EntityRenderer.cpp.s
.PHONY : src/rendering/renders/EntityRenderer.s

# target to generate assembly for a file
src/rendering/renders/EntityRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/EntityRenderer.cpp.s
.PHONY : src/rendering/renders/EntityRenderer.cpp.s

src/rendering/renders/HeightmapEntityRenderer.o: src/rendering/renders/HeightmapEntityRenderer.cpp.o
.PHONY : src/rendering/renders/HeightmapEntityRenderer.o

# target to build an object file
src/rendering/renders/HeightmapEntityRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/HeightmapEntityRenderer.cpp.o
.PHONY : src/rendering/renders/HeightmapEntityRenderer.cpp.o

src/rendering/renders/HeightmapEntityRenderer.i: src/rendering/renders/HeightmapEntityRenderer.cpp.i
.PHONY : src/rendering/renders/HeightmapEntityRenderer.i

# target to preprocess a source file
src/rendering/renders/HeightmapEntityRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/HeightmapEntityRenderer.cpp.i
.PHONY : src/rendering/renders/HeightmapEntityRenderer.cpp.i

src/rendering/renders/HeightmapEntityRenderer.s: src/rendering/renders/HeightmapEntityRenderer.cpp.s
.PHONY : src/rendering/renders/HeightmapEntityRenderer.s

# target to generate assembly for a file
src/rendering/renders/HeightmapEntityRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/HeightmapEntityRenderer.cpp.s
.PHONY : src/rendering/renders/HeightmapEntityRenderer.cpp.s

src/rendering/renders/MasterRenderer.o: src/rendering/renders/MasterRenderer.cpp.o
.PHONY : src/rendering/renders/MasterRenderer.o

# target to build an object file
src/rendering/renders/MasterRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/MasterRenderer.cpp.o
.PHONY : src/rendering/renders/MasterRenderer.cpp.o

src/rendering/renders/MasterRenderer.i: src/rendering/renders/MasterRenderer.cpp.i
.PHONY : src/rendering/renders/MasterRenderer.i

# target to preprocess a source file
src/rendering/renders/MasterRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/MasterRenderer.cpp.i
.PHONY : src/rendering/renders/MasterRenderer.cpp.i

src/rendering/renders/MasterRenderer.s: src/rendering/renders/MasterRenderer.cpp.s
.PHONY : src/rendering/renders/MasterRenderer.s

# target to generate assembly for a file
src/rendering/renders/MasterRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/MasterRenderer.cpp.s
.PHONY : src/rendering/renders/MasterRenderer.cpp.s

src/rendering/renders/shaders/BaseEntityShader.o: src/rendering/renders/shaders/BaseEntityShader.cpp.o
.PHONY : src/rendering/renders/shaders/BaseEntityShader.o

# target to build an object file
src/rendering/renders/shaders/BaseEntityShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/BaseEntityShader.cpp.o
.PHONY : src/rendering/renders/shaders/BaseEntityShader.cpp.o

src/rendering/renders/shaders/BaseEntityShader.i: src/rendering/renders/shaders/BaseEntityShader.cpp.i
.PHONY : src/rendering/renders/shaders/BaseEntityShader.i

# target to preprocess a source file
src/rendering/renders/shaders/BaseEntityShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/BaseEntityShader.cpp.i
.PHONY : src/rendering/renders/shaders/BaseEntityShader.cpp.i

src/rendering/renders/shaders/BaseEntityShader.s: src/rendering/renders/shaders/BaseEntityShader.cpp.s
.PHONY : src/rendering/renders/shaders/BaseEntityShader.s

# target to generate assembly for a file
src/rendering/renders/shaders/BaseEntityShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/BaseEntityShader.cpp.s
.PHONY : src/rendering/renders/shaders/BaseEntityShader.cpp.s

src/rendering/renders/shaders/BaseLitEntityShader.o: src/rendering/renders/shaders/BaseLitEntityShader.cpp.o
.PHONY : src/rendering/renders/shaders/BaseLitEntityShader.o

# target to build an object file
src/rendering/renders/shaders/BaseLitEntityShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/BaseLitEntityShader.cpp.o
.PHONY : src/rendering/renders/shaders/BaseLitEntityShader.cpp.o

src/rendering/renders/shaders/BaseLitEntityShader.i: src/rendering/renders/shaders/BaseLitEntityShader.cpp.i
.PHONY : src/rendering/renders/shaders/BaseLitEntityShader.i

# target to preprocess a source file
src/rendering/renders/shaders/BaseLitEntityShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/BaseLitEntityShader.cpp.i
.PHONY : src/rendering/renders/shaders/BaseLitEntityShader.cpp.i

src/rendering/renders/shaders/BaseLitEntityShader.s: src/rendering/renders/shaders/BaseLitEntityShader.cpp.s
.PHONY : src/rendering/renders/shaders/BaseLitEntityShader.s

# target to generate assembly for a file
src/rendering/renders/shaders/BaseLitEntityShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/BaseLitEntityShader.cpp.s
.PHONY : src/rendering/renders/shaders/BaseLitEntityShader.cpp.s

src/rendering/renders/shaders/HeightmapLitEntityShader.o: src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.o
.PHONY : src/rendering/renders/shaders/HeightmapLitEntityShader.o

# target to build an object file
src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.o
.PHONY : src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.o

src/rendering/renders/shaders/HeightmapLitEntityShader.i: src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.i
.PHONY : src/rendering/renders/shaders/HeightmapLitEntityShader.i

# target to preprocess a source file
src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.i
.PHONY : src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.i

src/rendering/renders/shaders/HeightmapLitEntityShader.s: src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.s
.PHONY : src/rendering/renders/shaders/HeightmapLitEntityShader.s

# target to generate assembly for a file
src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.s
.PHONY : src/rendering/renders/shaders/HeightmapLitEntityShader.cpp.s

src/rendering/renders/shaders/ShaderInterface.o: src/rendering/renders/shaders/ShaderInterface.cpp.o
.PHONY : src/rendering/renders/shaders/ShaderInterface.o

# target to build an object file
src/rendering/renders/shaders/ShaderInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/ShaderInterface.cpp.o
.PHONY : src/rendering/renders/shaders/ShaderInterface.cpp.o

src/rendering/renders/shaders/ShaderInterface.i: src/rendering/renders/shaders/ShaderInterface.cpp.i
.PHONY : src/rendering/renders/shaders/ShaderInterface.i

# target to preprocess a source file
src/rendering/renders/shaders/ShaderInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/ShaderInterface.cpp.i
.PHONY : src/rendering/renders/shaders/ShaderInterface.cpp.i

src/rendering/renders/shaders/ShaderInterface.s: src/rendering/renders/shaders/ShaderInterface.cpp.s
.PHONY : src/rendering/renders/shaders/ShaderInterface.s

# target to generate assembly for a file
src/rendering/renders/shaders/ShaderInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/renders/shaders/ShaderInterface.cpp.s
.PHONY : src/rendering/renders/shaders/ShaderInterface.cpp.s

src/rendering/resources/MeshHierarchy.o: src/rendering/resources/MeshHierarchy.cpp.o
.PHONY : src/rendering/resources/MeshHierarchy.o

# target to build an object file
src/rendering/resources/MeshHierarchy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/MeshHierarchy.cpp.o
.PHONY : src/rendering/resources/MeshHierarchy.cpp.o

src/rendering/resources/MeshHierarchy.i: src/rendering/resources/MeshHierarchy.cpp.i
.PHONY : src/rendering/resources/MeshHierarchy.i

# target to preprocess a source file
src/rendering/resources/MeshHierarchy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/MeshHierarchy.cpp.i
.PHONY : src/rendering/resources/MeshHierarchy.cpp.i

src/rendering/resources/MeshHierarchy.s: src/rendering/resources/MeshHierarchy.cpp.s
.PHONY : src/rendering/resources/MeshHierarchy.s

# target to generate assembly for a file
src/rendering/resources/MeshHierarchy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/MeshHierarchy.cpp.s
.PHONY : src/rendering/resources/MeshHierarchy.cpp.s

src/rendering/resources/ModelLoader.o: src/rendering/resources/ModelLoader.cpp.o
.PHONY : src/rendering/resources/ModelLoader.o

# target to build an object file
src/rendering/resources/ModelLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/ModelLoader.cpp.o
.PHONY : src/rendering/resources/ModelLoader.cpp.o

src/rendering/resources/ModelLoader.i: src/rendering/resources/ModelLoader.cpp.i
.PHONY : src/rendering/resources/ModelLoader.i

# target to preprocess a source file
src/rendering/resources/ModelLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/ModelLoader.cpp.i
.PHONY : src/rendering/resources/ModelLoader.cpp.i

src/rendering/resources/ModelLoader.s: src/rendering/resources/ModelLoader.cpp.s
.PHONY : src/rendering/resources/ModelLoader.s

# target to generate assembly for a file
src/rendering/resources/ModelLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/ModelLoader.cpp.s
.PHONY : src/rendering/resources/ModelLoader.cpp.s

src/rendering/resources/TextureHandle.o: src/rendering/resources/TextureHandle.cpp.o
.PHONY : src/rendering/resources/TextureHandle.o

# target to build an object file
src/rendering/resources/TextureHandle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/TextureHandle.cpp.o
.PHONY : src/rendering/resources/TextureHandle.cpp.o

src/rendering/resources/TextureHandle.i: src/rendering/resources/TextureHandle.cpp.i
.PHONY : src/rendering/resources/TextureHandle.i

# target to preprocess a source file
src/rendering/resources/TextureHandle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/TextureHandle.cpp.i
.PHONY : src/rendering/resources/TextureHandle.cpp.i

src/rendering/resources/TextureHandle.s: src/rendering/resources/TextureHandle.cpp.s
.PHONY : src/rendering/resources/TextureHandle.s

# target to generate assembly for a file
src/rendering/resources/TextureHandle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/TextureHandle.cpp.s
.PHONY : src/rendering/resources/TextureHandle.cpp.s

src/rendering/resources/TextureLoader.o: src/rendering/resources/TextureLoader.cpp.o
.PHONY : src/rendering/resources/TextureLoader.o

# target to build an object file
src/rendering/resources/TextureLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/TextureLoader.cpp.o
.PHONY : src/rendering/resources/TextureLoader.cpp.o

src/rendering/resources/TextureLoader.i: src/rendering/resources/TextureLoader.cpp.i
.PHONY : src/rendering/resources/TextureLoader.i

# target to preprocess a source file
src/rendering/resources/TextureLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/TextureLoader.cpp.i
.PHONY : src/rendering/resources/TextureLoader.cpp.i

src/rendering/resources/TextureLoader.s: src/rendering/resources/TextureLoader.cpp.s
.PHONY : src/rendering/resources/TextureLoader.s

# target to generate assembly for a file
src/rendering/resources/TextureLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/resources/TextureLoader.cpp.s
.PHONY : src/rendering/resources/TextureLoader.cpp.s

src/rendering/scene/Animator.o: src/rendering/scene/Animator.cpp.o
.PHONY : src/rendering/scene/Animator.o

# target to build an object file
src/rendering/scene/Animator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/Animator.cpp.o
.PHONY : src/rendering/scene/Animator.cpp.o

src/rendering/scene/Animator.i: src/rendering/scene/Animator.cpp.i
.PHONY : src/rendering/scene/Animator.i

# target to preprocess a source file
src/rendering/scene/Animator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/Animator.cpp.i
.PHONY : src/rendering/scene/Animator.cpp.i

src/rendering/scene/Animator.s: src/rendering/scene/Animator.cpp.s
.PHONY : src/rendering/scene/Animator.s

# target to generate assembly for a file
src/rendering/scene/Animator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/Animator.cpp.s
.PHONY : src/rendering/scene/Animator.cpp.s

src/rendering/scene/Lights.o: src/rendering/scene/Lights.cpp.o
.PHONY : src/rendering/scene/Lights.o

# target to build an object file
src/rendering/scene/Lights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/Lights.cpp.o
.PHONY : src/rendering/scene/Lights.cpp.o

src/rendering/scene/Lights.i: src/rendering/scene/Lights.cpp.i
.PHONY : src/rendering/scene/Lights.i

# target to preprocess a source file
src/rendering/scene/Lights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/Lights.cpp.i
.PHONY : src/rendering/scene/Lights.cpp.i

src/rendering/scene/Lights.s: src/rendering/scene/Lights.cpp.s
.PHONY : src/rendering/scene/Lights.s

# target to generate assembly for a file
src/rendering/scene/Lights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/Lights.cpp.s
.PHONY : src/rendering/scene/Lights.cpp.s

src/rendering/scene/MasterRenderScene.o: src/rendering/scene/MasterRenderScene.cpp.o
.PHONY : src/rendering/scene/MasterRenderScene.o

# target to build an object file
src/rendering/scene/MasterRenderScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/MasterRenderScene.cpp.o
.PHONY : src/rendering/scene/MasterRenderScene.cpp.o

src/rendering/scene/MasterRenderScene.i: src/rendering/scene/MasterRenderScene.cpp.i
.PHONY : src/rendering/scene/MasterRenderScene.i

# target to preprocess a source file
src/rendering/scene/MasterRenderScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/MasterRenderScene.cpp.i
.PHONY : src/rendering/scene/MasterRenderScene.cpp.i

src/rendering/scene/MasterRenderScene.s: src/rendering/scene/MasterRenderScene.cpp.s
.PHONY : src/rendering/scene/MasterRenderScene.s

# target to generate assembly for a file
src/rendering/scene/MasterRenderScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/rendering/scene/MasterRenderScene.cpp.s
.PHONY : src/rendering/scene/MasterRenderScene.cpp.s

src/scene/BasicStaticScene.o: src/scene/BasicStaticScene.cpp.o
.PHONY : src/scene/BasicStaticScene.o

# target to build an object file
src/scene/BasicStaticScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/BasicStaticScene.cpp.o
.PHONY : src/scene/BasicStaticScene.cpp.o

src/scene/BasicStaticScene.i: src/scene/BasicStaticScene.cpp.i
.PHONY : src/scene/BasicStaticScene.i

# target to preprocess a source file
src/scene/BasicStaticScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/BasicStaticScene.cpp.i
.PHONY : src/scene/BasicStaticScene.cpp.i

src/scene/BasicStaticScene.s: src/scene/BasicStaticScene.cpp.s
.PHONY : src/scene/BasicStaticScene.s

# target to generate assembly for a file
src/scene/BasicStaticScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/BasicStaticScene.cpp.s
.PHONY : src/scene/BasicStaticScene.cpp.s

src/scene/EditorScene.o: src/scene/EditorScene.cpp.o
.PHONY : src/scene/EditorScene.o

# target to build an object file
src/scene/EditorScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/EditorScene.cpp.o
.PHONY : src/scene/EditorScene.cpp.o

src/scene/EditorScene.i: src/scene/EditorScene.cpp.i
.PHONY : src/scene/EditorScene.i

# target to preprocess a source file
src/scene/EditorScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/EditorScene.cpp.i
.PHONY : src/scene/EditorScene.cpp.i

src/scene/EditorScene.s: src/scene/EditorScene.cpp.s
.PHONY : src/scene/EditorScene.s

# target to generate assembly for a file
src/scene/EditorScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/EditorScene.cpp.s
.PHONY : src/scene/EditorScene.cpp.s

src/scene/SceneManager.o: src/scene/SceneManager.cpp.o
.PHONY : src/scene/SceneManager.o

# target to build an object file
src/scene/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/SceneManager.cpp.o
.PHONY : src/scene/SceneManager.cpp.o

src/scene/SceneManager.i: src/scene/SceneManager.cpp.i
.PHONY : src/scene/SceneManager.i

# target to preprocess a source file
src/scene/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/SceneManager.cpp.i
.PHONY : src/scene/SceneManager.cpp.i

src/scene/SceneManager.s: src/scene/SceneManager.cpp.s
.PHONY : src/scene/SceneManager.s

# target to generate assembly for a file
src/scene/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/SceneManager.cpp.s
.PHONY : src/scene/SceneManager.cpp.s

src/scene/editor_scene/AnimatedEntityElement.o: src/scene/editor_scene/AnimatedEntityElement.cpp.o
.PHONY : src/scene/editor_scene/AnimatedEntityElement.o

# target to build an object file
src/scene/editor_scene/AnimatedEntityElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/AnimatedEntityElement.cpp.o
.PHONY : src/scene/editor_scene/AnimatedEntityElement.cpp.o

src/scene/editor_scene/AnimatedEntityElement.i: src/scene/editor_scene/AnimatedEntityElement.cpp.i
.PHONY : src/scene/editor_scene/AnimatedEntityElement.i

# target to preprocess a source file
src/scene/editor_scene/AnimatedEntityElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/AnimatedEntityElement.cpp.i
.PHONY : src/scene/editor_scene/AnimatedEntityElement.cpp.i

src/scene/editor_scene/AnimatedEntityElement.s: src/scene/editor_scene/AnimatedEntityElement.cpp.s
.PHONY : src/scene/editor_scene/AnimatedEntityElement.s

# target to generate assembly for a file
src/scene/editor_scene/AnimatedEntityElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/AnimatedEntityElement.cpp.s
.PHONY : src/scene/editor_scene/AnimatedEntityElement.cpp.s

src/scene/editor_scene/DirectionalLightElement.o: src/scene/editor_scene/DirectionalLightElement.cpp.o
.PHONY : src/scene/editor_scene/DirectionalLightElement.o

# target to build an object file
src/scene/editor_scene/DirectionalLightElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/DirectionalLightElement.cpp.o
.PHONY : src/scene/editor_scene/DirectionalLightElement.cpp.o

src/scene/editor_scene/DirectionalLightElement.i: src/scene/editor_scene/DirectionalLightElement.cpp.i
.PHONY : src/scene/editor_scene/DirectionalLightElement.i

# target to preprocess a source file
src/scene/editor_scene/DirectionalLightElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/DirectionalLightElement.cpp.i
.PHONY : src/scene/editor_scene/DirectionalLightElement.cpp.i

src/scene/editor_scene/DirectionalLightElement.s: src/scene/editor_scene/DirectionalLightElement.cpp.s
.PHONY : src/scene/editor_scene/DirectionalLightElement.s

# target to generate assembly for a file
src/scene/editor_scene/DirectionalLightElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/DirectionalLightElement.cpp.s
.PHONY : src/scene/editor_scene/DirectionalLightElement.cpp.s

src/scene/editor_scene/EmissiveEntityElement.o: src/scene/editor_scene/EmissiveEntityElement.cpp.o
.PHONY : src/scene/editor_scene/EmissiveEntityElement.o

# target to build an object file
src/scene/editor_scene/EmissiveEntityElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/EmissiveEntityElement.cpp.o
.PHONY : src/scene/editor_scene/EmissiveEntityElement.cpp.o

src/scene/editor_scene/EmissiveEntityElement.i: src/scene/editor_scene/EmissiveEntityElement.cpp.i
.PHONY : src/scene/editor_scene/EmissiveEntityElement.i

# target to preprocess a source file
src/scene/editor_scene/EmissiveEntityElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/EmissiveEntityElement.cpp.i
.PHONY : src/scene/editor_scene/EmissiveEntityElement.cpp.i

src/scene/editor_scene/EmissiveEntityElement.s: src/scene/editor_scene/EmissiveEntityElement.cpp.s
.PHONY : src/scene/editor_scene/EmissiveEntityElement.s

# target to generate assembly for a file
src/scene/editor_scene/EmissiveEntityElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/EmissiveEntityElement.cpp.s
.PHONY : src/scene/editor_scene/EmissiveEntityElement.cpp.s

src/scene/editor_scene/EntityElement.o: src/scene/editor_scene/EntityElement.cpp.o
.PHONY : src/scene/editor_scene/EntityElement.o

# target to build an object file
src/scene/editor_scene/EntityElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/EntityElement.cpp.o
.PHONY : src/scene/editor_scene/EntityElement.cpp.o

src/scene/editor_scene/EntityElement.i: src/scene/editor_scene/EntityElement.cpp.i
.PHONY : src/scene/editor_scene/EntityElement.i

# target to preprocess a source file
src/scene/editor_scene/EntityElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/EntityElement.cpp.i
.PHONY : src/scene/editor_scene/EntityElement.cpp.i

src/scene/editor_scene/EntityElement.s: src/scene/editor_scene/EntityElement.cpp.s
.PHONY : src/scene/editor_scene/EntityElement.s

# target to generate assembly for a file
src/scene/editor_scene/EntityElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/EntityElement.cpp.s
.PHONY : src/scene/editor_scene/EntityElement.cpp.s

src/scene/editor_scene/GroupElement.o: src/scene/editor_scene/GroupElement.cpp.o
.PHONY : src/scene/editor_scene/GroupElement.o

# target to build an object file
src/scene/editor_scene/GroupElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/GroupElement.cpp.o
.PHONY : src/scene/editor_scene/GroupElement.cpp.o

src/scene/editor_scene/GroupElement.i: src/scene/editor_scene/GroupElement.cpp.i
.PHONY : src/scene/editor_scene/GroupElement.i

# target to preprocess a source file
src/scene/editor_scene/GroupElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/GroupElement.cpp.i
.PHONY : src/scene/editor_scene/GroupElement.cpp.i

src/scene/editor_scene/GroupElement.s: src/scene/editor_scene/GroupElement.cpp.s
.PHONY : src/scene/editor_scene/GroupElement.s

# target to generate assembly for a file
src/scene/editor_scene/GroupElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/GroupElement.cpp.s
.PHONY : src/scene/editor_scene/GroupElement.cpp.s

src/scene/editor_scene/HeightmapEntityElement.o: src/scene/editor_scene/HeightmapEntityElement.cpp.o
.PHONY : src/scene/editor_scene/HeightmapEntityElement.o

# target to build an object file
src/scene/editor_scene/HeightmapEntityElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/HeightmapEntityElement.cpp.o
.PHONY : src/scene/editor_scene/HeightmapEntityElement.cpp.o

src/scene/editor_scene/HeightmapEntityElement.i: src/scene/editor_scene/HeightmapEntityElement.cpp.i
.PHONY : src/scene/editor_scene/HeightmapEntityElement.i

# target to preprocess a source file
src/scene/editor_scene/HeightmapEntityElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/HeightmapEntityElement.cpp.i
.PHONY : src/scene/editor_scene/HeightmapEntityElement.cpp.i

src/scene/editor_scene/HeightmapEntityElement.s: src/scene/editor_scene/HeightmapEntityElement.cpp.s
.PHONY : src/scene/editor_scene/HeightmapEntityElement.s

# target to generate assembly for a file
src/scene/editor_scene/HeightmapEntityElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/HeightmapEntityElement.cpp.s
.PHONY : src/scene/editor_scene/HeightmapEntityElement.cpp.s

src/scene/editor_scene/PointLightElement.o: src/scene/editor_scene/PointLightElement.cpp.o
.PHONY : src/scene/editor_scene/PointLightElement.o

# target to build an object file
src/scene/editor_scene/PointLightElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/PointLightElement.cpp.o
.PHONY : src/scene/editor_scene/PointLightElement.cpp.o

src/scene/editor_scene/PointLightElement.i: src/scene/editor_scene/PointLightElement.cpp.i
.PHONY : src/scene/editor_scene/PointLightElement.i

# target to preprocess a source file
src/scene/editor_scene/PointLightElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/PointLightElement.cpp.i
.PHONY : src/scene/editor_scene/PointLightElement.cpp.i

src/scene/editor_scene/PointLightElement.s: src/scene/editor_scene/PointLightElement.cpp.s
.PHONY : src/scene/editor_scene/PointLightElement.s

# target to generate assembly for a file
src/scene/editor_scene/PointLightElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/PointLightElement.cpp.s
.PHONY : src/scene/editor_scene/PointLightElement.cpp.s

src/scene/editor_scene/SceneElement.o: src/scene/editor_scene/SceneElement.cpp.o
.PHONY : src/scene/editor_scene/SceneElement.o

# target to build an object file
src/scene/editor_scene/SceneElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/SceneElement.cpp.o
.PHONY : src/scene/editor_scene/SceneElement.cpp.o

src/scene/editor_scene/SceneElement.i: src/scene/editor_scene/SceneElement.cpp.i
.PHONY : src/scene/editor_scene/SceneElement.i

# target to preprocess a source file
src/scene/editor_scene/SceneElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/SceneElement.cpp.i
.PHONY : src/scene/editor_scene/SceneElement.cpp.i

src/scene/editor_scene/SceneElement.s: src/scene/editor_scene/SceneElement.cpp.s
.PHONY : src/scene/editor_scene/SceneElement.s

# target to generate assembly for a file
src/scene/editor_scene/SceneElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/scene/editor_scene/SceneElement.cpp.s
.PHONY : src/scene/editor_scene/SceneElement.cpp.s

src/system_interfaces/Window.o: src/system_interfaces/Window.cpp.o
.PHONY : src/system_interfaces/Window.o

# target to build an object file
src/system_interfaces/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/system_interfaces/Window.cpp.o
.PHONY : src/system_interfaces/Window.cpp.o

src/system_interfaces/Window.i: src/system_interfaces/Window.cpp.i
.PHONY : src/system_interfaces/Window.i

# target to preprocess a source file
src/system_interfaces/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/system_interfaces/Window.cpp.i
.PHONY : src/system_interfaces/Window.cpp.i

src/system_interfaces/Window.s: src/system_interfaces/Window.cpp.s
.PHONY : src/system_interfaces/Window.s

# target to generate assembly for a file
src/system_interfaces/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/system_interfaces/Window.cpp.s
.PHONY : src/system_interfaces/Window.cpp.s

src/system_interfaces/WindowManager.o: src/system_interfaces/WindowManager.cpp.o
.PHONY : src/system_interfaces/WindowManager.o

# target to build an object file
src/system_interfaces/WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/system_interfaces/WindowManager.cpp.o
.PHONY : src/system_interfaces/WindowManager.cpp.o

src/system_interfaces/WindowManager.i: src/system_interfaces/WindowManager.cpp.i
.PHONY : src/system_interfaces/WindowManager.i

# target to preprocess a source file
src/system_interfaces/WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/system_interfaces/WindowManager.cpp.i
.PHONY : src/system_interfaces/WindowManager.cpp.i

src/system_interfaces/WindowManager.s: src/system_interfaces/WindowManager.cpp.s
.PHONY : src/system_interfaces/WindowManager.s

# target to generate assembly for a file
src/system_interfaces/WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/system_interfaces/WindowManager.cpp.s
.PHONY : src/system_interfaces/WindowManager.cpp.s

src/utility/OpenGL.o: src/utility/OpenGL.cpp.o
.PHONY : src/utility/OpenGL.o

# target to build an object file
src/utility/OpenGL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/OpenGL.cpp.o
.PHONY : src/utility/OpenGL.cpp.o

src/utility/OpenGL.i: src/utility/OpenGL.cpp.i
.PHONY : src/utility/OpenGL.i

# target to preprocess a source file
src/utility/OpenGL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/OpenGL.cpp.i
.PHONY : src/utility/OpenGL.cpp.i

src/utility/OpenGL.s: src/utility/OpenGL.cpp.s
.PHONY : src/utility/OpenGL.s

# target to generate assembly for a file
src/utility/OpenGL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/OpenGL.cpp.s
.PHONY : src/utility/OpenGL.cpp.s

src/utility/PerformanceCounter.o: src/utility/PerformanceCounter.cpp.o
.PHONY : src/utility/PerformanceCounter.o

# target to build an object file
src/utility/PerformanceCounter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/PerformanceCounter.cpp.o
.PHONY : src/utility/PerformanceCounter.cpp.o

src/utility/PerformanceCounter.i: src/utility/PerformanceCounter.cpp.i
.PHONY : src/utility/PerformanceCounter.i

# target to preprocess a source file
src/utility/PerformanceCounter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/PerformanceCounter.cpp.i
.PHONY : src/utility/PerformanceCounter.cpp.i

src/utility/PerformanceCounter.s: src/utility/PerformanceCounter.cpp.s
.PHONY : src/utility/PerformanceCounter.s

# target to generate assembly for a file
src/utility/PerformanceCounter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/PerformanceCounter.cpp.s
.PHONY : src/utility/PerformanceCounter.cpp.s

src/utility/SyncManager.o: src/utility/SyncManager.cpp.o
.PHONY : src/utility/SyncManager.o

# target to build an object file
src/utility/SyncManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/SyncManager.cpp.o
.PHONY : src/utility/SyncManager.cpp.o

src/utility/SyncManager.i: src/utility/SyncManager.cpp.i
.PHONY : src/utility/SyncManager.i

# target to preprocess a source file
src/utility/SyncManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/SyncManager.cpp.i
.PHONY : src/utility/SyncManager.cpp.i

src/utility/SyncManager.s: src/utility/SyncManager.cpp.s
.PHONY : src/utility/SyncManager.s

# target to generate assembly for a file
src/utility/SyncManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cits3003_project.dir/build.make CMakeFiles/cits3003_project.dir/src/utility/SyncManager.cpp.s
.PHONY : src/utility/SyncManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... assimp"
	@echo "... cits3003_project"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... stb"
	@echo "... tinyfiledialogs"
	@echo "... zlibstatic"
	@echo "... src/feature/simplex.o"
	@echo "... src/feature/simplex.i"
	@echo "... src/feature/simplex.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/rendering/cameras/FlyingCamera.o"
	@echo "... src/rendering/cameras/FlyingCamera.i"
	@echo "... src/rendering/cameras/FlyingCamera.s"
	@echo "... src/rendering/cameras/PanningCamera.o"
	@echo "... src/rendering/cameras/PanningCamera.i"
	@echo "... src/rendering/cameras/PanningCamera.s"
	@echo "... src/rendering/imgui/ImGuiImpl.o"
	@echo "... src/rendering/imgui/ImGuiImpl.i"
	@echo "... src/rendering/imgui/ImGuiImpl.s"
	@echo "... src/rendering/imgui/ImGuiManager.o"
	@echo "... src/rendering/imgui/ImGuiManager.i"
	@echo "... src/rendering/imgui/ImGuiManager.s"
	@echo "... src/rendering/renders/AnimatedEntityRenderer.o"
	@echo "... src/rendering/renders/AnimatedEntityRenderer.i"
	@echo "... src/rendering/renders/AnimatedEntityRenderer.s"
	@echo "... src/rendering/renders/EmissiveEntityRenderer.o"
	@echo "... src/rendering/renders/EmissiveEntityRenderer.i"
	@echo "... src/rendering/renders/EmissiveEntityRenderer.s"
	@echo "... src/rendering/renders/EntityRenderer.o"
	@echo "... src/rendering/renders/EntityRenderer.i"
	@echo "... src/rendering/renders/EntityRenderer.s"
	@echo "... src/rendering/renders/HeightmapEntityRenderer.o"
	@echo "... src/rendering/renders/HeightmapEntityRenderer.i"
	@echo "... src/rendering/renders/HeightmapEntityRenderer.s"
	@echo "... src/rendering/renders/MasterRenderer.o"
	@echo "... src/rendering/renders/MasterRenderer.i"
	@echo "... src/rendering/renders/MasterRenderer.s"
	@echo "... src/rendering/renders/shaders/BaseEntityShader.o"
	@echo "... src/rendering/renders/shaders/BaseEntityShader.i"
	@echo "... src/rendering/renders/shaders/BaseEntityShader.s"
	@echo "... src/rendering/renders/shaders/BaseLitEntityShader.o"
	@echo "... src/rendering/renders/shaders/BaseLitEntityShader.i"
	@echo "... src/rendering/renders/shaders/BaseLitEntityShader.s"
	@echo "... src/rendering/renders/shaders/HeightmapLitEntityShader.o"
	@echo "... src/rendering/renders/shaders/HeightmapLitEntityShader.i"
	@echo "... src/rendering/renders/shaders/HeightmapLitEntityShader.s"
	@echo "... src/rendering/renders/shaders/ShaderInterface.o"
	@echo "... src/rendering/renders/shaders/ShaderInterface.i"
	@echo "... src/rendering/renders/shaders/ShaderInterface.s"
	@echo "... src/rendering/resources/MeshHierarchy.o"
	@echo "... src/rendering/resources/MeshHierarchy.i"
	@echo "... src/rendering/resources/MeshHierarchy.s"
	@echo "... src/rendering/resources/ModelLoader.o"
	@echo "... src/rendering/resources/ModelLoader.i"
	@echo "... src/rendering/resources/ModelLoader.s"
	@echo "... src/rendering/resources/TextureHandle.o"
	@echo "... src/rendering/resources/TextureHandle.i"
	@echo "... src/rendering/resources/TextureHandle.s"
	@echo "... src/rendering/resources/TextureLoader.o"
	@echo "... src/rendering/resources/TextureLoader.i"
	@echo "... src/rendering/resources/TextureLoader.s"
	@echo "... src/rendering/scene/Animator.o"
	@echo "... src/rendering/scene/Animator.i"
	@echo "... src/rendering/scene/Animator.s"
	@echo "... src/rendering/scene/Lights.o"
	@echo "... src/rendering/scene/Lights.i"
	@echo "... src/rendering/scene/Lights.s"
	@echo "... src/rendering/scene/MasterRenderScene.o"
	@echo "... src/rendering/scene/MasterRenderScene.i"
	@echo "... src/rendering/scene/MasterRenderScene.s"
	@echo "... src/scene/BasicStaticScene.o"
	@echo "... src/scene/BasicStaticScene.i"
	@echo "... src/scene/BasicStaticScene.s"
	@echo "... src/scene/EditorScene.o"
	@echo "... src/scene/EditorScene.i"
	@echo "... src/scene/EditorScene.s"
	@echo "... src/scene/SceneManager.o"
	@echo "... src/scene/SceneManager.i"
	@echo "... src/scene/SceneManager.s"
	@echo "... src/scene/editor_scene/AnimatedEntityElement.o"
	@echo "... src/scene/editor_scene/AnimatedEntityElement.i"
	@echo "... src/scene/editor_scene/AnimatedEntityElement.s"
	@echo "... src/scene/editor_scene/DirectionalLightElement.o"
	@echo "... src/scene/editor_scene/DirectionalLightElement.i"
	@echo "... src/scene/editor_scene/DirectionalLightElement.s"
	@echo "... src/scene/editor_scene/EmissiveEntityElement.o"
	@echo "... src/scene/editor_scene/EmissiveEntityElement.i"
	@echo "... src/scene/editor_scene/EmissiveEntityElement.s"
	@echo "... src/scene/editor_scene/EntityElement.o"
	@echo "... src/scene/editor_scene/EntityElement.i"
	@echo "... src/scene/editor_scene/EntityElement.s"
	@echo "... src/scene/editor_scene/GroupElement.o"
	@echo "... src/scene/editor_scene/GroupElement.i"
	@echo "... src/scene/editor_scene/GroupElement.s"
	@echo "... src/scene/editor_scene/HeightmapEntityElement.o"
	@echo "... src/scene/editor_scene/HeightmapEntityElement.i"
	@echo "... src/scene/editor_scene/HeightmapEntityElement.s"
	@echo "... src/scene/editor_scene/PointLightElement.o"
	@echo "... src/scene/editor_scene/PointLightElement.i"
	@echo "... src/scene/editor_scene/PointLightElement.s"
	@echo "... src/scene/editor_scene/SceneElement.o"
	@echo "... src/scene/editor_scene/SceneElement.i"
	@echo "... src/scene/editor_scene/SceneElement.s"
	@echo "... src/system_interfaces/Window.o"
	@echo "... src/system_interfaces/Window.i"
	@echo "... src/system_interfaces/Window.s"
	@echo "... src/system_interfaces/WindowManager.o"
	@echo "... src/system_interfaces/WindowManager.i"
	@echo "... src/system_interfaces/WindowManager.s"
	@echo "... src/utility/OpenGL.o"
	@echo "... src/utility/OpenGL.i"
	@echo "... src/utility/OpenGL.s"
	@echo "... src/utility/PerformanceCounter.o"
	@echo "... src/utility/PerformanceCounter.i"
	@echo "... src/utility/PerformanceCounter.s"
	@echo "... src/utility/SyncManager.o"
	@echo "... src/utility/SyncManager.i"
	@echo "... src/utility/SyncManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

